### ISSUE TITLE
Problem on data frame filtering for legacy data.

### ISSUE THREAD

**Issue by Yassid** [ATTPC/spyral_notebooks#1]
Bug found when displaying 16O+alpha legacy data without a valid IC spectrum.

Commenting the data frame filtering gives the error "LazyFrame object has no attribute 'to_numpy'". This can be bypassed by using .to_numpy().collect(). However, removing the comment (and keeping the modification) gives another error "'DataFrame' object has no attribute 'collect'".

**Comment by gwm17** [comment]
This is now fixed (kinda). Though if anyone runs into this issue again (or a similar issue), I recommend looking at the polars docs on Lazy vs. Eager [here](https://docs.pola.rs/user-guide/concepts/lazy-vs-eager/). Not so much a bug, as the notebook being a little unclear as to what was happening. Either way, I think the change I made should make this more difficult to make happen.
